travis:
  secure:
    BINSTAR_TOKEN: K+cqqvQkakuiV6WNJr48kGRJXUokWYJO0BtIRulS4fiITr72FBmNXY8o62xrKtKttXgCAPCCEtobv8lk54JHZGmwfqP8Lv8hJBV/2QTdF++472qArbiADoDjbaeVhI0ziZorku7JJ68W9slfUMELA/TyuLxBf1FL3tUFAOl6qKZfPlW8X9HjUjB4qHmYBrUTPrJ9yvA/XdipZ4xSmoGPJ3xINbkiQAq1403L1zP9i+XzniivB7DWpKM4RpPMlCxnA4WDhAiFSycg/gMhdcis5D76ru1KVif0+h57aNr6PZhX9eDF+omdjiqZVnzuGeG7YjoLX8urh7B/9KHYTGs2WNtYI/UPw6RSCq51EXhmIMsIFo9wo0hP+cXf63oXFGa7d78e/k1OT9GakccbhO0n4o+ASNc3z5xDlxW77I0KPciuZwcUx23aIeJ943kEpjMNru2J2fw+l9PwY29Yiwpu1Z7hwNthM0euW+DTnWMI0mz5t1l/6Doxeqn4WLI7zh25vPBgL4Vr3EgfzIpHFVT+I3ZVPAKDTx2H6JEI3t2PW+M5a9oyY1QQOPbsoFWEwq3am8nb6A879BbjKr078wpRAEWFJ0kSnBMZyuoGaGP0K4aPoY8xZvOzORe98WOm+UnMETpjsbV+bEla7RDN8UpLFd93eXU7dUESq199SV9toAs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
